Add e2e test
cybozu-go/necoperf pull request #9
Opened 2023-10-02 06:19 UTC by zeroalphat

2023-10-27 09:23 UTC, umezawatakeshi commented
It seems OK for now (except Dockerfile.daemon)

2023-10-27 12:01 UTC, morimoto-cybozu requested changes

2023-10-27 12:01 UTC, morimoto-cybozu commented on e2e/suite_test.go
> +		if err != nil {
This is just a matter of preference.
You can use Gomega's assertions even in `Eventually()`.

```
Eventually(func(g Gomega) {
  ...
  g.Expect(err).NotTo(HaveOccurred())
  ...
}).Should(Succeed())
```

2023-10-30 06:39 UTC, morimoto-cybozu requested changes

2023-10-30 06:39 UTC, morimoto-cybozu commented on e2e/Makefile
> +setup: bin_dir kubectl kustomize kind
`bin_dir` is no longer necessary.

2023-10-30 06:39 UTC, morimoto-cybozu commented on e2e/Makefile
> +	mkdir -p $(BIN_DIR)
ditto

2023-10-30 07:14 UTC, morimoto-cybozu approved these changes
LGTM

2023-11-08 06:29 UTC, umezawatakeshi approved these changes

2023-11-08 06:54 UTC, morimoto-cybozu approved these changes

2023-11-08 06:56 UTC, merged